export const dummyContent = {
  root: {
    type: 'root',
    children: [
      {
        type: 'paragraph',
        children: [
          {
            type: 'text',
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Hello World! Welcome to RootEditor!!',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        textFormat: 0,
        version: 1,
      },
      {
        type: 'heading',
        children: [
          {
            type: 'text',
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'HelloWorld',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        tag: 'h2',
        version: 1,
      },
      {
        type: 'heading',
        children: [
          {
            type: 'text',
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'H3',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        tag: 'h3',
        version: 1,
      },
      {
        type: 'paragraph',
        children: [
          {
            type: 'text',
            detail: 0,
            format: 0,
            mode: 'normal',
            style: 'color: #c82929;',
            text: 'Link',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: 'center',
        indent: 0,
        textFormat: 0,
        version: 1,
      },
      {
        type: 'paragraph',
        children: [
          {
            type: 'text',
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'FirstSTageLogo',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: 'center',
        indent: 0,
        textFormat: 0,
        version: 1,
      },
      {
        type: 'paragraph',
        children: [
          {
            type: 'image',
            altText: '',
            caption: {
              editorState: {
                root: {
                  type: 'root',
                  children: [],
                  direction: null,
                  format: '',
                  indent: 0,
                  version: 1,
                },
              },
            },
            height: 500,
            maxWidth: 500,
            showCaption: false,
            src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAuIwAALiMBeKU/dgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAI2SURBVHic7d1NSsNgFIXhU0HFBQgK7sQddFKd6B4diE7cgWtRcAHaOqiD0DbWSvqT3Hu+5H3hgskk3+1DHZV2pFVjSY+STkVpjdauQUnuSNKkdv0i6V7SLOc4JFUv/s3avbGkL0lzJnw0B8Vqln+A4jG/LkDJnz83QDEDAcUQBBRDEFAMQUAxBAHFEAQUQxBQDEFAMQQBxRAEFEMQUAxBQDEEAcUQBBRDEFAMQUAxBAHFEAQUQxBQ9pjRQqXDZpLuJD3X7l1KOuv4uW11Iek18oER8pveKaV0pdh3SdiDppLO23udwgoFOQpaSpJOxIe4G4sEoS0CxCxAzALELEDMAsQsQMwCxCxAzALELEDMAsQsQMwCxCxAzALELEDMAsQsQMwCxCxAzALELEDMAsQsQMwCxCxAzALELEDMAsQsQMwCxCxAzALELEDMAsQsQMwCxCxAzAKkuakCf5MLkOY+JN2qgum8iC+fqXct6T3weYf0Kemtdj2R9KDqGyk6LfKLVUqarK+WSl/ceTJQ0pd2n2iU9IVLmEiU9GVLmSiU9EVLmgiU9CVLm65R0hcscbpESV+u1OkKJX2xkqcLlPSlSp+2UdIX6sO0iZK+TF+mLZT0Rfo0baCkL9G3ORQlfYE+ziEo6Yfv6+yLkn7wPs8+KOmH7vvsipJ+4CHMLijphx3KbIuSftAhzTYo6Ycc2jShpB9wiPMvSvQH5WjVpl+vmwCS27cqlKfFDT7bm9uxqo+nLv99/QDcil45oqFZGgAAAABJRU5ErkJggg==',
            version: 1,
            width: 500,
          },
        ],
        direction: null,
        format: 'left',
        indent: 0,
        textFormat: 0,
        version: 1,
      },
      {
        type: 'paragraph',
        children: [],
        direction: 'ltr',
        format: 'center',
        indent: 0,
        textFormat: 0,
        version: 1,
      },
      {
        type: 'layout-container',
        children: [
          {
            type: 'layout-item',
            children: [
              {
                type: 'paragraph',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Column Test',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                textFormat: 0,
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
          {
            type: 'layout-item',
            children: [
              {
                type: 'paragraph',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Column Test2',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                textFormat: 0,
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        templateColumns: '1fr 1fr',
        version: 1,
      },
      {
        type: 'table',
        children: [
          {
            type: 'tablerow',
            children: [
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '1',
                        version: 1,
                      },
                    ],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 3,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '2',
                        version: 1,
                      },
                    ],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 1,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '3',
                        version: 1,
                      },
                    ],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 1,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '4',
                        version: 1,
                      },
                    ],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 1,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '5',
                        version: 1,
                      },
                    ],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 1,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
            ],
            direction: null,
            format: '',
            indent: 0,
            version: 1,
          },
          {
            type: 'tablerow',
            children: [
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 2,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
            ],
            direction: null,
            format: '',
            indent: 0,
            version: 1,
          },
          {
            type: 'tablerow',
            children: [
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 2,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
            ],
            direction: null,
            format: '',
            indent: 0,
            version: 1,
          },
          {
            type: 'tablerow',
            children: [
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 2,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
            ],
            direction: null,
            format: '',
            indent: 0,
            version: 1,
          },
          {
            type: 'tablerow',
            children: [
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 2,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
              {
                type: 'tablecell',
                backgroundColor: null,
                children: [
                  {
                    type: 'paragraph',
                    children: [],
                    direction: null,
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                colSpan: 1,
                direction: null,
                format: '',
                headerState: 0,
                indent: 0,
                rowSpan: 1,
                version: 1,
              },
            ],
            direction: null,
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
      {
        type: 'paragraph',
        children: [],
        direction: null,
        format: '',
        indent: 0,
        textFormat: 0,
        version: 1,
      },
      {
        type: 'paragraph',
        children: [],
        direction: null,
        format: 'center',
        indent: 0,
        textFormat: 0,
        version: 1,
      },
    ],
    direction: 'ltr',
    format: '',
    indent: 0,
    version: 1,
  },
};

export const titleDummy = {
  root: {
    type: 'root',
    children: [
      {
        type: 'heading',
        children: [],
        direction: null,
        format: '',
        indent: 0,
        tag: 'h1',
        version: 1,
      },
    ],
    direction: null,
    format: '',
    indent: 0,
    version: 1,
  },
};
