name: Continuous Integration

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: ./.github/actions/node-pnpm-setup

      - name: Install Dependencies
        run: pnpm i
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Lint
        if: ${{ always() }}
        run: pnpm run lint

      - name: Test
        if: ${{ always() }}
        run: pnpm run test

      - name: Build
        run: pnpm run build

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
