name: Storybook Build & Deployment at Github Page

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: ./.github/actions/node-pnpm-setup

      - name: Install Dependencies
        run: pnpm i
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build Storybook
        run: pnpm run storybook:build

      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: storybook
          folder: docs
