name: Publish Artifacts at Github Packages

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: ./.github/actions/node-pnpm-setup

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm run build

      - run: pnpm publish
