name: Publish Artifacts at Github Packages

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: ./.github/actions/node-pnpm-setup

      - name: Install Dependencies
        run: pnpm i
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build
        run: pnpm run build

      - run: pnpm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
